In [68]:

import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)
print(type(arr))
print(np.__version__)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1.16.5


In [69]:
arr=np.array([[1,2,3],[4,5,6]])

In [70]:
arr
print(arr.ndim)

2


In [71]:
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[9,0],[11,12]]])

In [72]:
print(arr.ndim)
arr

3


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9,  0],
        [11, 12]]])

In [73]:
#5-d
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [74]:
#indexing
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [75]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1])


2nd element on 1st dim:  2


In [76]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -3])

Last element from 2nd dim:  8


In [77]:
#slicing
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
#Note: The result includes the start index, but excludes the end index

[2 3 4 5]


In [78]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [79]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


# 2-d slicing

In [80]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [81]:
##*
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


# Data types


i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )


In [82]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [83]:
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [84]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [85]:
#For i, u, f, S and U we can define size as well
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [86]:
arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

In [87]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [88]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [89]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('S')

print(newarr)
print(newarr.dtype)

[b'1.1' b'2.1' b'3.1']
|S32


In [2]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [3]:
#copy
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[1 2 3 4 5]


In [6]:
#view
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)



[42  2  3  4  5]
[42  2  3  4  5]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)


[42  2  3  4  5]
[42  2  3  4  5]
